// swift-tools-version: 5.9
// Distribution manifest for https://github.com/Pixelnetica/DocScanningSDK-iOS.
// Generated by scripts/package-xcframeworks.sh --dist 3.0.0 in the
// DocScanning-SDK-iOS working repo; mirrors DSSDK-Framework/Package.swift
// (path-based development manifest). Do not edit by hand — regenerate.
import PackageDescription

let package = Package(
    name: "DocScanningSDK",
    platforms: [.iOS("16.3")],
    products: [
        .library(name: "DocScanningSDK", targets: ["DocScanningSDK"]),
        .library(name: "DocScanningSDK-UI", targets: ["DocScanningSDK-UI", "DocScanningSDK"]),
    ],
    targets: [
        .binaryTarget(
            name: "DocScanningSDK",
            url: "https://github.com/Pixelnetica/DocScanningSDK-iOS/releases/download/3.0.0/DocScanningSDK.xcframework.zip",
            checksum: "429a1bd94eb827c2535650d278eb6fc55b358694c5d79afb29d0f095cf81a4ce"
        ),
        .binaryTarget(
            name: "DocScanningSDK-UI",
            url: "https://github.com/Pixelnetica/DocScanningSDK-iOS/releases/download/3.0.0/DocScanningSDK-UI.xcframework.zip",
            checksum: "28f76798ae2e959c0f128c7e58b34c2e74b9c8dcfe2e40163f9897c8452b0c54"
        ),
    ]
)
