// swift-tools-version: 5.9
// Distribution manifest for https://github.com/Pixelnetica/DocScanningSDK-iOS.
// Generated by scripts/package-xcframeworks.sh --dist 3.1.2-beta.1 in the
// DocScanning-SDK-iOS working repo; mirrors DSSDK-Framework/Package.swift
// (path-based development manifest). Do not edit by hand — regenerate.
import PackageDescription

let package = Package(
    name: "DocScanningSDK",
    platforms: [.iOS("16.3")],
    products: [
        .library(name: "DocScanningSDK", targets: ["DocScanningSDK"]),
        .library(name: "DocScanningSDK-UI", targets: ["DocScanningSDK-UI", "DocScanningSDK"]),
    ],
    targets: [
        .binaryTarget(
            name: "DocScanningSDK",
            url: "https://github.com/Pixelnetica/DocScanningSDK-iOS/releases/download/3.1.2-beta.1/DocScanningSDK.xcframework.zip",
            checksum: "9cfb0d3a9c66c803a7aa81875e6c77d7c27f1fcdec3308391370643a0ebb9216"
        ),
        .binaryTarget(
            name: "DocScanningSDK-UI",
            url: "https://github.com/Pixelnetica/DocScanningSDK-iOS/releases/download/3.1.2-beta.1/DocScanningSDK-UI.xcframework.zip",
            checksum: "9cdd9d3c22fa20f02e87e49777bf71bf7a9c574272308b77668682be4904be7a"
        ),
    ]
)
