// swift-tools-version: 5.9
// Distribution manifest for https://github.com/Pixelnetica/DocScanningSDK-iOS.
// Generated by scripts/package-xcframeworks.sh --dist 3.0.0 in the
// DocScanning-SDK-iOS working repo; mirrors DSSDK-Framework/Package.swift
// (path-based development manifest). Do not edit by hand — regenerate.
import PackageDescription

let package = Package(
    name: "DocScanningSDK",
    platforms: [.iOS("16.3")],
    products: [
        .library(name: "DocScanningSDK", targets: ["DocScanningSDK"]),
        .library(name: "DocScanningSDK-UI", targets: ["DocScanningSDK-UI", "DocScanningSDK"]),
    ],
    targets: [
        .binaryTarget(
            name: "DocScanningSDK",
            url: "https://github.com/Pixelnetica/DocScanningSDK-iOS/releases/download/3.0.0/DocScanningSDK.xcframework.zip",
            checksum: "66e3a72c5450cfe456dcc933af2e6e03a15568655ae9e38990a24a5960fbc44c"
        ),
        .binaryTarget(
            name: "DocScanningSDK-UI",
            url: "https://github.com/Pixelnetica/DocScanningSDK-iOS/releases/download/3.0.0/DocScanningSDK-UI.xcframework.zip",
            checksum: "376b80faad92af9bc2dba0b8f854c15c17649923ac58a7004bda988dfa3c6782"
        ),
    ]
)
